services:
  app:
    image: ${DOCKER_IMAGE}
    container_name: code-agent-app
    build:
      context: .
      target: "service"
    ports:
      - 127.0.0.1:${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    environment:
      APP_SERVICE: app
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy        

  db:
    image: postgres:17-alpine
    container_name: code-agent-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - ${PWD}/.data/postgres:/var/lib/postgresql/data/pgdata

  test:
    container_name: code-agent-test
    image: code-agent:test
    env_file:
      - .env
    build:
      context: .
      target: tests
      args:
        DEV_DEPS: true
    environment:
      APP_SERVICE: test
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

  lint:
    container_name: code-agent-lint
    image: code-agent:test
    env_file:
      - .env
    build:
      context: .
      target: tests
      args:
        DEV_DEPS: true
    environment:
      APP_SERVICE: lint
