services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_TOKEN=your-secret-token
      - SERVICE_TOKENS={"service1":"token1","service2":"token2"}
      - ENABLE_SWAGGER=true
    volumes:
      - ./src:/src/src
    restart: unless-stopped 

  test:
    image:
      code-agent:test
    build:
      context: .
      args:
        DEV_DEPS: "true"
    env_file:
      - .env
    environment:
      - APP_SERVICE=test
    volumes:
      - ${PWD}/.local:/app/.local

  lint:
    image:
      code-agent:test
    build:
      context: .
      args:
        DEV_DEPS: "true"
    env_file:
      - .env
    environment:
      - APP_SERVICE=lint
    volumes:
      - ${PWD}/src:/src/src
      - ${PWD}/.local:/app/.local
    command: >
      sh -c "black --check src/ &&
             isort --check-only src/ &&
             mypy src/ &&
             ruff check src/"
