services:
  api:
    build: .
    ports:
      - "127.0.0.1:8003:8000"
    env_file:
      - .env
    environment:
      APP_SERVICE: "web"
      APP_HOST: "0.0.0.0"
      APP_PORT: "8000"
    volumes:
      - ./src:/src/src
    restart: unless-stopped 

  test:
    image:
      code-agent:test
    build:
      context: .
      args:
        DEV_DEPS: "true"
    env_file:
      - .env
    environment:
      - APP_SERVICE=test
    volumes:
      - ${PWD}/.local:/app/.local

  lint:
    image:
      code-agent:test
    build:
      context: .
      args:
        DEV_DEPS: "true"
    env_file:
      - .env
    environment:
      - APP_SERVICE=lint
    volumes:
      - ${PWD}/src:/src/src
      - ${PWD}/.local:/app/.local
    command: >
      sh -c "black --check src/ &&
             isort --check-only src/ &&
             mypy src/ &&
             ruff check src/"
