version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_TOKEN=your-secret-token
      - SERVICE_TOKENS={"service1":"token1","service2":"token2"}
      - ENABLE_SWAGGER=true
    volumes:
      - ./src:/src/src
    restart: unless-stopped 

  test:
    image:
      code-agent:test
    build:
      context: .
      args:
        DEV_DEPS: "true"
    env_file:
      - .env
    environment:
      - APP_SERVICE=test
    volumes:
      - ${PWD}/.data:/app/.data
