services:
  api:
    build:
      context: .
      target: "service"
    ports:
      - "127.0.0.1:8003:8000"
    env_file:
      - .env
    environment:
      APP_SERVICE: "web"
      APP_HOST: "0.0.0.0"
      APP_PORT: "8000"
    volumes:
      - ./src:/src/src
    depends_on:
      - postgres
    restart: unless-stopped 

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: code_agent
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  test:
    image:
      code-agent:test
    build:
      context: .
      target: "tests"
      args:
        DEV_DEPS: "true"
    environment:
      - APP_SERVICE=test
    volumes:
      - ${PWD}/.local:/app/.local

  lint:
    image:
      code-agent:test
    build:
      context: .
      target: "tests"
      args:
        DEV_DEPS: "true"
    environment:
      - APP_SERVICE=lint

volumes:
  postgres_data:
