#!/bin/sh

set -e

# check that all required environment variables are set
if [ -z "${DB_USER}" ] || [ -z "${DB_PASSWORD}" ] || [ -z "${DB_NAME}" ]; then
  echo "Error: Required environment variables are not set" >&2
  exit 1
fi


print_caption() {
  echo "===================="
  echo "$1"
  echo "===================="
  echo ""
}


if [ "${APP_SERVICE}" = "app" ]
  then
    print_caption "Start DB migrations"
    alembic upgrade head
    print_caption "Start app"
    python -m src.main

elif [ "${APP_SERVICE}" = "test" ]
  then
    print_caption "Lint check"
    export RUFF_CACHE_DIR=/tmp/.ruff
    ruff check
    print_caption "Test"
    coverage run -m pytest -o cache_dir=/tmp && \

elif [ "${APP_SERVICE}" = "lint" ]
  then
    print_caption "Black check"
    black --check .
    print_caption "Lint check"
    export RUFF_CACHE_DIR=/tmp/.ruff
    ruff check .
    print_caption "Mypy check"
    mypy .

else
  echo "APP_SERVICE environment variable is unexpected or was not provided (APP_SERVICE='${APP_SERVICE}')" >&2
  kill -s SIGINT 1

fi
