#!/bin/sh

set -e

if [ "${APP_SERVICE}" = "web" ]
  then
#    echo "=========="
#    echo "Start DB migrations"
#    echo "=========="
#    echo ""
#    alembic upgrade head
    python -m src.main

elif [ "${APP_SERVICE}" = "test" ]
  then
    echo "=== ruff ==="
    export RUFF_CACHE_DIR=/tmp/.ruff
    ruff check
    export COVERAGE_FILE=/tmp/.coverage
    coverage run -m pytest -o cache_dir=/tmp && \
    coverage report --omit="src/tests/*"

elif [ "${APP_SERVICE}" = "lint" ]
  then
    echo "=== black ==="
    black --check .
    echo "=== ruff ==="
    export RUFF_CACHE_DIR=/tmp/.ruff
    ruff check .
    echo "=== mypy ==="
    mypy .

else
  echo "APP_SERVICE environment variable is unexpected or was not provided (APP_SERVICE='${APP_SERVICE}')" >&2
  kill -s SIGINT 1

fi
