services:
  api:
    image: ${DOCKER_IMAGE}
    container_name: 'code-agent'
    env_file:
      - .env
    environment:
      - APP_SERVICE=web
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=code_agent
      - DB_PASSWORD=4uUDDypJyOHuhPyiQ
      - DB_DATABASE=code_agent
    volumes:
      - ${PWD}/.data:/src/.data
    ports:
      - 127.0.0.1:${APP_PORT}:${APP_PORT}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: code_agent
      POSTGRES_PASSWORD: 4uUDDypJyOHuhPyiQ
      POSTGRES_DB: code_agent
    volumes:
      - ${PWD}/.data/postgres:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 2s
      retries: 5
    restart: unless-stopped
